@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Nov 04 14:39:27 +0200 2025
REM SW Build 5076996 on Wed May 22 18:37:14 MDT 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim top_tb_behav -key {Behavioral:sim_1:Functional:top_tb} -tclbatch top_tb.tcl -view C:/Users/andre/IMPORTANT/FACULTATE/AN IV/SI Sisteme Embedded/Proiect/AudioModulator_V0/top_tb_behav.wcfg -view C:/Users/andre/IMPORTANT/FACULTATE/AN IV/SI Sisteme Embedded/Proiect/AudioModulator_V0/audio_i2c.wcfg -view C:/Users/andre/IMPORTANT/FACULTATE/AN IV/SI Sisteme Embedded/Proiect/AudioModulator_V0/audio_i2s.wcfg -view C:/Users/andre/IMPORTANT/FACULTATE/AN IV/SI Sisteme Embedded/Proiect/AudioModulator_V0/mac_mdio_behav.wcfg -view C:/Users/andre/IMPORTANT/FACULTATE/AN IV/SI Sisteme Embedded/Proiect/AudioModulator_V0/mac_rx_behav.wcfg -view C:/Users/andre/IMPORTANT/FACULTATE/AN IV/SI Sisteme Embedded/Proiect/AudioModulator_V0/mac_tx_behav.wcfg -log simulate.log"
call xsim  top_tb_behav -key {Behavioral:sim_1:Functional:top_tb} -tclbatch top_tb.tcl -view C:/Users/andre/IMPORTANT/FACULTATE/AN IV/SI Sisteme Embedded/Proiect/AudioModulator_V0/top_tb_behav.wcfg -view C:/Users/andre/IMPORTANT/FACULTATE/AN IV/SI Sisteme Embedded/Proiect/AudioModulator_V0/audio_i2c.wcfg -view C:/Users/andre/IMPORTANT/FACULTATE/AN IV/SI Sisteme Embedded/Proiect/AudioModulator_V0/audio_i2s.wcfg -view C:/Users/andre/IMPORTANT/FACULTATE/AN IV/SI Sisteme Embedded/Proiect/AudioModulator_V0/mac_mdio_behav.wcfg -view C:/Users/andre/IMPORTANT/FACULTATE/AN IV/SI Sisteme Embedded/Proiect/AudioModulator_V0/mac_rx_behav.wcfg -view C:/Users/andre/IMPORTANT/FACULTATE/AN IV/SI Sisteme Embedded/Proiect/AudioModulator_V0/mac_tx_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
